import { AuthErrorCodes } from "firebase/auth";

type AuthErrorCode = (typeof AuthErrorCodes)[keyof typeof AuthErrorCodes];

/**
 * The error codes for FireBase Authentication. They can be customized here.
 * If they are not customized, the default error messages are used.
 */
export const authErrors: Record<AuthErrorCode, string> = {
  "auth/weak-password":
    "Das Passwort ist zu schwach. Bitte gib mindestens 6 Zeichen ein.",
  "auth/email-already-in-use": "Diese E-Mail-Adresse wird bereits verwendet.",
  "auth/wrong-password": "Das eingegebene Passwort ist falsch.",
  "auth/too-many-requests":
    "Zu viele Anfragen. Bitte versuche es später erneut.",
  "auth/user-not-found":
    "Es existiert kein Benutzer mit dieser E-Mail-Adresse.",
  "auth/invalid-email":
    "Die angegebene E-Mail-Adresse ist ungültig. Bitte gib eine gültige E-Mail-Adresse ein.",
  "auth/requires-recent-login":
    "Bitte melde dich erneut an, um diese Aktion durchzuführen.",

  // Uncustomized error codes
  "auth/admin-restricted-operation": "",
  "auth/argument-error": "",
  "auth/app-not-authorized": "",
  "auth/app-not-installed": "",
  "auth/captcha-check-failed": "",
  "auth/code-expired": "",
  "auth/cordova-not-ready": "",
  "auth/cors-unsupported": "",
  "auth/credential-already-in-use": "",
  "auth/custom-token-mismatch": "",
  "auth/dependent-sdk-initialized-before-auth": "",
  "auth/dynamic-link-not-activated": "",
  "auth/email-change-needs-verification": "",
  "auth/emulator-config-failed": "",
  "auth/expired-action-code": "",
  "auth/cancelled-popup-request": "",
  "auth/internal-error": "",
  "auth/invalid-api-key": "",
  "auth/invalid-app-credential": "",
  "auth/invalid-app-id": "",
  "auth/invalid-user-token": "",
  "auth/invalid-auth-event": "",
  "auth/invalid-cert-hash": "",
  "auth/invalid-verification-code": "",
  "auth/invalid-continue-uri": "",
  "auth/invalid-cordova-configuration": "",
  "auth/invalid-custom-token": "",
  "auth/invalid-dynamic-link-domain": "",
  "auth/invalid-emulator-scheme": "",
  "auth/invalid-credential": "",
  "auth/invalid-message-payload": "",
  "auth/invalid-multi-factor-session": "",
  "auth/invalid-oauth-client-id": "",
  "auth/invalid-oauth-provider": "",
  "auth/invalid-action-code": "",
  "auth/unauthorized-domain": "",
  "auth/invalid-persistence-type": "",
  "auth/invalid-phone-number": "",
  "auth/invalid-provider-id": "",
  "auth/invalid-recipient-email": "",
  "auth/invalid-sender": "",
  "auth/invalid-verification-id": "",
  "auth/invalid-tenant-id": "",
  "auth/multi-factor-info-not-found": "",
  "auth/multi-factor-auth-required": "",
  "auth/missing-android-pkg-name": "",
  "auth/missing-app-credential": "",
  "auth/auth-domain-config-required": "",
  "auth/missing-verification-code": "",
  "auth/missing-continue-uri": "",
  "auth/missing-iframe-start": "",
  "auth/missing-ios-bundle-id": "",
  "auth/missing-or-invalid-nonce": "",
  "auth/missing-multi-factor-info": "",
  "auth/missing-multi-factor-session": "",
  "auth/missing-phone-number": "",
  "auth/missing-verification-id": "",
  "auth/app-deleted": "",
  "auth/account-exists-with-different-credential": "",
  "auth/network-request-failed": "",
  "auth/null-user": "",
  "auth/no-auth-event": "",
  "auth/no-such-provider": "",
  "auth/operation-not-allowed": "",
  "auth/operation-not-supported-in-this-environment": "",
  "auth/popup-blocked": "",
  "auth/popup-closed-by-user": "",
  "auth/provider-already-linked": "",
  "auth/quota-exceeded": "",
  "auth/redirect-cancelled-by-user": "",
  "auth/redirect-operation-pending": "",
  "auth/rejected-credential": "",
  "auth/second-factor-already-in-use": "",
  "auth/maximum-second-factor-count-exceeded": "",
  "auth/tenant-id-mismatch": "",
  "auth/timeout": "",
  "auth/user-token-expired": "",
  "auth/unauthorized-continue-uri": "",
  "auth/unsupported-first-factor": "",
  "auth/unsupported-persistence-type": "",
  "auth/unsupported-tenant-operation": "",
  "auth/unverified-email": "",
  "auth/user-cancelled": "",
  "auth/user-disabled": "",
  "auth/user-mismatch": "",
  "auth/user-signed-out": "",
  "auth/web-storage-unsupported": "",
  "auth/already-initialized": "",
  "auth/recaptcha-not-enabled": "",
  "auth/missing-recaptcha-token": "",
  "auth/invalid-recaptcha-token": "",
  "auth/invalid-recaptcha-action": "",
  "auth/missing-client-type": "",
  "auth/missing-recaptcha-version": "",
  "auth/invalid-recaptcha-version": "",
  "auth/invalid-req-type": "",
};

export const getAuthError = (code: string) => {
  const message = authErrors[code as keyof typeof authErrors];
  return message ? `${message} (${code})` : undefined;
};
